### ISSUE TITLE
Too much widget rebuild occurring when using PanelBuilder [BETA]

### ISSUE THREAD

**Issue by rohansohonee** [akshathjain/sliding_up_panel#94]
Hi @akshathjain 

Just started playing around with the new PanelBuilder (beta) using this code snippet from your example docs:
``` dart
// The sliding up panel
SlidingUpPanel(
      panelBuilder: (ScrollController sc) => _scrollingList(sc),
      body: Center(
        child: Text("This is the Widget behind the sliding panel"),
      ),
)
// The scrolling list
Widget _scrollingList(ScrollController sc) {
    print('scrolling list rebuilt');
    return ListView.builder(
      controller: sc,
      itemCount: 50,
      itemBuilder: (BuildContext context, int i) {
        return Container(
          padding: const EdgeInsets.all(12.0),
          child: Text("$i"),
        );
      },
    );
  }
```

- I added a print statement ``print('scrolling list rebuilt');``.
- PanelBuilder (beta) keeps rebuilding the widget when scrolling the list. This need to be fixed.

Console log output for reference:
``` console
I/flutter ( 9831): scrolling list rebuilt
I/flutter ( 9831): scrolling list rebuilt
I/flutter ( 9831): scrolling list rebuilt
I/flutter ( 9831): scrolling list rebuilt
I/flutter ( 9831): scrolling list rebuilt
I/flutter ( 9831): scrolling list rebuilt
```

> NOTE: When adding ``setState`` calls inside _scrollingList widget, it causes even more drastic performance issues as the widget gets rebuilt multiple times.

**Comment by akshathjain** [comment]
@rohansohonee I profiled the sample code and got render times at < 4 ms / frame which is substantially less than the 16 ms / frame that Flutter recommends to maintain 60 FPS. 

However, it is unnecessary to rebuild the panelBuilder widget on each animation tick as the panel slides up and down (which is currently occurring). This will be resolved in the next update.

**Comment by ozburo** [comment]
@akshathjain just wanted to say that this update saved me! Got my Sliding Panel > PanelBuilder > CustomScrollView working like a charm! 

Thanks 🥇

**Comment by biklas7** [comment]
Hi, @akshathjain I'm having heavy performance problems with this.  Glad to know you're working on it! Thanks for the awesome package :+1:

**Comment by surveshoeb** [comment]
@akshathjain have fixed this issue?

**Comment by s0nerik** [comment]
Looks like I've fixed it in https://github.com/akshathjain/sliding_up_panel/pull/112

**Comment by akshathjain** [comment]
Thanks to @s0nerik's PR, I'm closing this issue. This fix will be pushed to prod within the next 24 hours.

**Comment by LarYoungruu** [comment]
Hi @akshathjain 
Has this been fixed or not?
I tried and found the problem is still there (2.0.0+1)

![Screen Shot 2021-07-15 at 5 19 21 PM](https://user-images.githubusercontent.com/45846101/125772352-06674c95-a574-467f-8f69-d8c40a936390.png)

**Comment by mqhamdam** [comment]
come here with the same problem. Cannot use panelbuilder with gridview. It rebuilds children on scroll max/min height

**Comment by CagriYonca** [comment]
Hi everyone,

I don't know why but the problem is still going on. I've used this solution as workaround and it worked, take a look:
https://github.com/akshathjain/sliding_up_panel/issues/188#issuecomment-835254625
